2020-10-03 17:27:20,874 ERROR: Exception on /index [GET] [in w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "W:\py\flask_project\micro_blog\blog_app\routes.py", line 31, in index
    return render_template('index.html', title='Microblog', form=form, posts=posts.items, next_url=next_url,
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "W:\py\flask_project\micro_blog\blog_app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "W:\py\flask_project\micro_blog\blog_app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "W:\py\flask_project\micro_blog\blog_app\templates\base.html", line 40, in block "navbar"
    <a href="{{ url_for('messages') }}">Messages
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'messages'. Did you mean 'register' instead?
2020-10-03 17:28:59,944 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:47]
2020-10-03 17:29:01,365 ERROR: Exception on / [GET] [in w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "W:\py\flask_project\micro_blog\blog_app\routes.py", line 31, in index
    return render_template('index.html', title='Microblog', form=form, posts=posts.items, next_url=next_url,
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "W:\py\flask_project\micro_blog\blog_app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "W:\py\flask_project\micro_blog\blog_app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "W:\py\flask_project\micro_blog\blog_app\templates\base.html", line 51, in block "navbar"
    <li><a href="{{ url_for('logout') }}">{{ _('Logout') }}</a></li>
jinja2.exceptions.UndefinedError: '_' is undefined
2020-10-03 17:29:31,119 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:47]
2020-10-03 17:33:18,436 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:47]
2020-10-03 18:47:28,690 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:50]
2020-10-03 20:50:48,089 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:52]
2020-10-03 21:02:31,089 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:52]
2020-10-03 21:19:06,450 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:52]
2020-10-03 21:19:29,841 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:52]
2020-10-03 21:19:52,279 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:52]
2020-10-04 14:57:42,740 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:52]
2020-10-04 14:57:54,240 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:52]
2020-10-04 16:21:11,847 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:52]
2020-10-04 16:25:21,108 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:52]
2020-10-04 16:54:27,883 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:52]
2020-10-04 16:58:03,516 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:52]
2020-10-04 17:01:22,390 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:52]
2020-10-04 17:01:39,576 INFO: Microblog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:52]
2020-10-05 11:23:28,573 INFO: MicroBlog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:70]
2020-10-05 11:26:35,430 INFO: MicroBlog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:70]
2020-10-05 11:31:20,416 INFO: MicroBlog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:70]
2020-10-05 11:34:18,406 INFO: MicroBlog startup [in W:\py\flask_project\micro_blog\blog_app\__init__.py:70]
