2020-10-21 22:13:34,012 ERROR: Exception on /api/users/2 [GET] [in w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "W:\py\Microblog\blog_app\api\users.py", line 7, in get_user
    return jsonify(User.query.get_or_404(id).to_dict())
  File "W:\py\Microblog\blog_app\models.py", line 144, in to_dict
    'last_seen': self.last_seen.isoformat() + 'Z',
AttributeError: 'NoneType' object has no attribute 'isoformat'
2020-10-21 22:15:12,565 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:80]
2020-10-21 22:20:39,741 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:80]
2020-10-21 22:21:02,455 ERROR: Exception on /api/users [GET] [in w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "W:\py\Microblog\blog_app\api\users.py", line 15, in get_users
    data = User.to_collection_dict(User.query, page, per_page, 'api.get_users')
  File "W:\py\Microblog\blog_app\models.py", line 25, in to_collection_dict
    'items': [item.to_dict() for item in resources.items],
  File "W:\py\Microblog\blog_app\models.py", line 25, in <listcomp>
    'items': [item.to_dict() for item in resources.items],
  File "W:\py\Microblog\blog_app\models.py", line 144, in to_dict
    'last_seen': self.last_seen.isoformat() + 'Z',
AttributeError: 'NoneType' object has no attribute 'isoformat'
2020-10-21 22:22:36,856 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:80]
2020-10-21 22:23:03,620 ERROR: Exception on /api/users [GET] [in w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "W:\py\Microblog\blog_app\api\users.py", line 15, in get_users
    data = User.to_collection_dict(User.query, page, per_page, 'api.get_users')
  File "W:\py\Microblog\blog_app\models.py", line 25, in to_collection_dict
    'items': [item.to_dict() for item in resources.items],
  File "W:\py\Microblog\blog_app\models.py", line 25, in <listcomp>
    'items': [item.to_dict() for item in resources.items],
  File "W:\py\Microblog\blog_app\models.py", line 144, in to_dict
    'last_seen': self.last_seen.isoformat()  + 'Z' or 'no data',
AttributeError: 'NoneType' object has no attribute 'isoformat'
2020-10-21 22:23:48,909 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:80]
2020-10-21 22:24:05,119 ERROR: Exception on /api/users [GET] [in w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "W:\py\Microblog\blog_app\api\users.py", line 15, in get_users
    data = User.to_collection_dict(User.query, page, per_page, 'api.get_users')
  File "W:\py\Microblog\blog_app\models.py", line 25, in to_collection_dict
    'items': [item.to_dict() for item in resources.items],
  File "W:\py\Microblog\blog_app\models.py", line 25, in <listcomp>
    'items': [item.to_dict() for item in resources.items],
  File "W:\py\Microblog\blog_app\models.py", line 144, in to_dict
    'last_seen': (self.last_seen.isoformat() + 'Z') or 'no data',
AttributeError: 'NoneType' object has no attribute 'isoformat'
2020-10-21 22:27:14,151 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:80]
2020-10-21 23:03:56,843 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:80]
2020-10-21 23:13:01,491 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:80]
2020-10-21 23:21:01,032 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:80]
