2020-10-16 17:11:56,435 ERROR: Exception on / [GET] [in w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "W:\py\Microblog\blog_app\main\routes.py", line 48, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items, next_url=next_url,
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "W:\py\Microblog\blog_app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "W:\py\Microblog\blog_app\templates\base.html", line 49, in template
    <li><a href="{{ url_for('main.messages'}}">{{ _('Messages') }}</a>
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2020-10-16 17:12:33,277 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-16 17:14:12,308 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-16 17:15:52,148 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-16 17:15:58,221 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-16 17:19:31,911 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-16 17:29:27,631 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-16 19:23:23,818 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-16 19:23:44,897 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-16 19:44:00,236 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-16 19:44:07,388 ERROR: Exception on / [GET] [in w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "W:\py\Microblog\blog_app\main\routes.py", line 48, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items, next_url=next_url,
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "W:\py\Microblog\blog_app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "w:\py\flask_project\micro_blog\blog_env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "W:\py\Microblog\blog_app\templates\base.html", line 158, in template
    endif %
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '%'
2020-10-16 19:44:41,941 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-16 20:33:35,424 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-17 09:54:54,359 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-17 09:58:59,042 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-17 11:13:11,282 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-17 11:19:34,750 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-17 11:39:55,682 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-17 12:00:22,573 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-17 12:00:32,313 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:73]
2020-10-17 16:26:01,033 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:78]
2020-10-17 16:27:59,313 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:78]
2020-10-17 16:29:22,972 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:78]
2020-10-17 16:33:40,352 INFO: MicroBlog startup [in W:\py\Microblog\blog_app\__init__.py:78]
